services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - DEBUG=1
      - SERVICES=s3,dynamodb,lambda,iam,organizations
      - PERSIST=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=local
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5
